spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://parking-booking-database:5432/postgres?currentSchema=booking&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    default-schema: booking
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/parking
          jwk-set-uri: http://keycloak:8180/realms/parking/protocol/openid-connect/certs
