spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://parking-booking-database:5432/postgres?currentSchema=account&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    default-schema: parking-booking